// lib/themePresets.ts
export const themePresets = {
  modern: {
    name: 'Modern',
    nameBn: 'আধুনিক',
    description: 'Clean and modern design with gradients',
    descriptionBn: 'পরিষ্কার এবং আধুনিক ডিজাইন গ্রেডিয়েন্ট সহ',
    themeImage: '/assets/themes/modern.png',
    icon: '✨',
    settings: {
      primaryColor: '#f58f19',
      secondaryColor: '#c06e11',
      accentColor: '#F59E0B',
      backgroundColor: '#FFFFFF',
      textColor: '#1F2937',
      headingColor: '#111827',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'default',
      hoverEffect: 'scale',
      gradientStart: '#c06e11',
      gradientEnd: '#dba260',
      gradientDirection: 'to-r',
      buttonPrimary: '#f58f19',
      buttonPrimaryHover: '#c06e11',
      buttonSecondary: '#bdad95',
      buttonSecondaryHover: '#f79d49',
      linkColor: '#f58f19',
      linkHover: '#c06e11',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#70a3f7',
      headerBackground: '#FFFFFF',
      footerBackground: '#ffffff',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB'
    }
  },
  classic: {
    name: 'Classic',
    nameBn: 'ক্লাসিক',
    description: 'Traditional e-commerce design',
    descriptionBn: 'ঐতিহ্যবাহী ইকমার্স ডিজাইন',
    themeImage: '/assets/themes/classic.png',
    icon: '📜',
    settings: {
      primaryColor: '#8B4513',
      secondaryColor: '#DAA520',
      accentColor: '#CD853F',
      backgroundColor: '#FDF5E6',
      textColor: '#4A3728',
      headingColor: '#3E2723',
      borderRadius: '0.25rem',
      cardStyle: 'bordered',
      buttonStyle: 'square',
      headerStyle: 'centered',
      footerStyle: 'default',
      hoverEffect: 'shadow',
      gradientStart: '#8B4513',
      gradientEnd: '#DAA520',
      gradientDirection: 'to-r',
      buttonPrimary: '#8B4513',
      buttonPrimaryHover: '#6B3410',
      buttonSecondary: '#DAA520',
      buttonSecondaryHover: '#B8860B',
      linkColor: '#8B4513',
      linkHover: '#6B3410',
      successColor: '#2E7D32',
      errorColor: '#C62828',
      warningColor: '#F57C00',
      infoColor: '#1565C0',
      headerBackground: '#FDF5E6',
      footerBackground: '#3E2723',
      cardBackground: '#FFFFFF',
      borderColor: '#D4A373'
    }
  },
  dark: {
    name: 'Dark Mode',
    nameBn: 'ডার্ক মোড',
    description: 'Modern dark theme for night browsing',
    descriptionBn: 'রাতে ব্রাউজিংয়ের জন্য আধুনিক ডার্ক থিম',
    icon: '🌙',
    settings: {
      primaryColor: '#3B82F6',
      secondaryColor: '#10B981',
      accentColor: '#F59E0B',
      backgroundColor: '#0F172A',
      textColor: '#F1F5F9',
      headingColor: '#FFFFFF',
      cardBackground: '#1E293B',
      borderColor: '#334155',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'glass',
      footerStyle: 'dark',
      hoverEffect: 'glow',
      gradientStart: '#3B82F6',
      gradientEnd: '#06B6D4',
      gradientDirection: 'to-r',
      buttonPrimary: '#3B82F6',
      buttonPrimaryHover: '#2563EB',
      buttonSecondary: '#10B981',
      buttonSecondaryHover: '#059669',
      linkColor: '#60A5FA',
      linkHover: '#93C5FD',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#0F172A',
      footerBackground: '#020617',
      textSecondary: '#94A3B8',
      textMuted: '#64748B'
    }
  },
  gradient: {
    name: 'Gradient',
    nameBn: 'গ্রেডিয়েন্ট',
    description: 'Vibrant gradient design',
    descriptionBn: 'উজ্জ্বল গ্রেডিয়েন্ট ডিজাইন',
    icon: '🌈',
    settings: {
      primaryColor: '#EC4899',
      secondaryColor: '#8B5CF6',
      accentColor: '#06B6D4',
      backgroundColor: '#FFFFFF',
      textColor: '#1F2937',
      headingColor: '#111827',
      borderRadius: '1rem',
      cardStyle: 'glass',
      buttonStyle: 'pill',
      headerStyle: 'glass',
      footerStyle: 'glass',
      hoverEffect: 'glow',
      gradientStart: '#EC4899',
      gradientEnd: '#8B5CF6',
      gradientDirection: 'to-r',
      buttonPrimary: '#EC4899',
      buttonPrimaryHover: '#DB2777',
      buttonSecondary: '#8B5CF6',
      buttonSecondaryHover: '#7C3AED',
      linkColor: '#EC4899',
      linkHover: '#DB2777',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#06B6D4',
      headerBackground: 'transparent',
      footerBackground: '#1F2937',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB'
    }
  },
  minimal: {
    name: 'Minimal',
    nameBn: 'মিনিমাল',
    description: 'Clean and simple design',
    descriptionBn: 'পরিষ্কার এবং সহজ ডিজাইন',
    icon: '⬜',
    settings: {
      primaryColor: '#000000',
      secondaryColor: '#333333',
      accentColor: '#666666',
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      headingColor: '#000000',
      borderRadius: '0rem',
      cardStyle: 'flat',
      buttonStyle: 'square',
      headerStyle: 'transparent',
      footerStyle: 'minimal',
      hoverEffect: 'none',
      gradientStart: '#000000',
      gradientEnd: '#333333',
      gradientDirection: 'to-r',
      buttonPrimary: '#000000',
      buttonPrimaryHover: '#333333',
      buttonSecondary: '#333333',
      buttonSecondaryHover: '#666666',
      linkColor: '#000000',
      linkHover: '#333333',
      successColor: '#000000',
      errorColor: '#000000',
      warningColor: '#333333',
      infoColor: '#666666',
      headerBackground: '#FFFFFF',
      footerBackground: '#F9FAFB',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB',
      textSecondary: '#6B7280',
      textMuted: '#9CA3AF'
    }
  },
  ocean: {
    name: 'Ocean',
    nameBn: 'সাগর',
    description: 'Calm blue ocean theme',
    descriptionBn: 'শান্ত নীল সাগর থিম',
    icon: '🌊',
    settings: {
      primaryColor: '#0EA5E9',
      secondaryColor: '#06B6D4',
      accentColor: '#F59E0B',
      backgroundColor: '#F0F9FF',
      textColor: '#0F172A',
      headingColor: '#0369A1',
      borderRadius: '0.75rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#0EA5E9',
      gradientEnd: '#06B6D4',
      gradientDirection: 'to-r',
      buttonPrimary: '#0EA5E9',
      buttonPrimaryHover: '#0284C7',
      buttonSecondary: '#06B6D4',
      buttonSecondaryHover: '#0891B2',
      linkColor: '#0EA5E9',
      linkHover: '#0284C7',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#0EA5E9',
      headerBackground: '#FFFFFF',
      footerBackground: '#0F172A',
      cardBackground: '#FFFFFF',
      borderColor: '#BAE6FD'
    }
  },
  forest: {
    name: 'Forest',
    nameBn: 'বন',
    description: 'Green nature inspired theme',
    descriptionBn: 'সবুজ প্রকৃতি অনুপ্রাণিত থিম',
    icon: '🌲',
    settings: {
      primaryColor: '#059669',
      secondaryColor: '#10B981',
      accentColor: '#F59E0B',
      backgroundColor: '#ECFDF5',
      textColor: '#064E3B',
      headingColor: '#065F46',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#059669',
      gradientEnd: '#10B981',
      gradientDirection: 'to-r',
      buttonPrimary: '#059669',
      buttonPrimaryHover: '#047857',
      buttonSecondary: '#10B981',
      buttonSecondaryHover: '#059669',
      linkColor: '#059669',
      linkHover: '#047857',
      successColor: '#059669',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#064E3B',
      cardBackground: '#FFFFFF',
      borderColor: '#A7F3D0'
    }
  },
  sunset: {
    name: 'Sunset',
    nameBn: 'সূর্যাস্ত',
    description: 'Warm sunset colors',
    descriptionBn: 'উষ্ণ সূর্যাস্তের রং',
    icon: '🌅',
    settings: {
      primaryColor: '#F97316',
      secondaryColor: '#EF4444',
      accentColor: '#F59E0B',
      backgroundColor: '#FFF7ED',
      textColor: '#431407',
      headingColor: '#9A3412',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#F97316',
      gradientEnd: '#EF4444',
      gradientDirection: 'to-r',
      buttonPrimary: '#F97316',
      buttonPrimaryHover: '#EA580C',
      buttonSecondary: '#EF4444',
      buttonSecondaryHover: '#DC2626',
      linkColor: '#F97316',
      linkHover: '#EA580C',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#431407',
      cardBackground: '#FFFFFF',
      borderColor: '#FED7AA'
    }
  },
  lavender: {
    name: 'Lavender',
    nameBn: 'ল্যাভেন্ডার',
    description: 'Soft purple theme',
    descriptionBn: 'নরম বেগুনি থিম',
    icon: '💜',
    settings: {
      primaryColor: '#8B5CF6',
      secondaryColor: '#A78BFA',
      accentColor: '#F59E0B',
      backgroundColor: '#FAF5FF',
      textColor: '#4C1D95',
      headingColor: '#6D28D9',
      borderRadius: '0.75rem',
      cardStyle: 'elevated',
      buttonStyle: 'pill',
      headerStyle: 'glass',
      footerStyle: 'dark',
      hoverEffect: 'glow',
      gradientStart: '#8B5CF6',
      gradientEnd: '#C084FC',
      gradientDirection: 'to-r',
      buttonPrimary: '#8B5CF6',
      buttonPrimaryHover: '#7C3AED',
      buttonSecondary: '#A78BFA',
      buttonSecondaryHover: '#8B5CF6',
      linkColor: '#8B5CF6',
      linkHover: '#7C3AED',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#4C1D95',
      cardBackground: '#FFFFFF',
      borderColor: '#E9D5FF'
    }
  }
};