// lib/themePresets.ts
export const themePresets = {
  modern: {
    name: 'Modern',
    nameBn: 'আধুনিক',
    description: 'Clean and modern design with gradients',
    descriptionBn: 'পরিষ্কার এবং আধুনিক ডিজাইন গ্রেডিয়েন্ট সহ',
    themeImage: '/assets/themes/modern.png',
    icon: '✨',
    settings: {
      primaryColor: '#f58f19',
      secondaryColor: '#c06e11',
      accentColor: '#F59E0B',
      backgroundColor: '#FFFFFF',
      textColor: '#1F2937',
      headingColor: '#111827',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'default',
      hoverEffect: 'scale',
      gradientStart: '#c06e11',
      gradientEnd: '#dba260',
      gradientDirection: 'to-r',
      buttonPrimary: '#f58f19',
      buttonPrimaryHover: '#c06e11',
      buttonSecondary: '#bdad95',
      buttonSecondaryHover: '#f79d49',
      linkColor: '#f58f19',
      linkHover: '#c06e11',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#70a3f7',
      headerBackground: '#FFFFFF',
      footerBackground: '#ffffff',
      cardBackground: '#FFFFFF',
      borderColor: '#E5E7EB'
    }
  },
  classic: {
    name: 'Classic',
    nameBn: 'ক্লাসিক',
    description: 'Traditional e-commerce design',
    descriptionBn: 'ঐতিহ্যবাহী ইকমার্স ডিজাইন',
    themeImage: '/assets/themes/classic.png',
    icon: '📜',
    settings: {
      primaryColor: '#059669',
      secondaryColor: '#F97316',
      accentColor: '#F59E0B',
      backgroundColor: '#F9FAFB',
      textColor: '#374151',
      headingColor: '#111827',
      borderRadius: '1rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#059669',
      gradientEnd: '#10B981',
      gradientDirection: 'to-br',
      buttonPrimary: '#059669',
      buttonPrimaryHover: '#047857',
      buttonSecondary: '#FFFFFF',
      buttonSecondaryHover: '#ECFDF5',
      linkColor: '#059669',
      linkHover: '#047857',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#0EA5E9',
      headerBackground: '#FFFFFF',
      footerBackground: '#111827',
      cardBackground: '#FFFFFF',
      borderColor: '#F3F4F6'
    }
  },
  dark: {
    name: 'Dark Mode',
    nameBn: 'ডার্ক মোড',
    description: 'Modern dark theme for night browsing',
    descriptionBn: 'রাতে ব্রাউজিংয়ের জন্য আধুনিক ডার্ক থিম',
    icon: '🌙',
    settings: {
      primaryColor: '#f58f19',
      secondaryColor: '#c06e11',
      accentColor: '#F59E0B',
      backgroundColor: '#1F2937',
      textColor: '#F9FAFB',
      headingColor: '#FFFFFF',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'glass',
      footerStyle: 'dark',
      hoverEffect: 'glow',
      gradientStart: '#c06e11',
      gradientEnd: '#dba260',
      gradientDirection: 'to-r',
      buttonPrimary: '#f58f19',
      buttonPrimaryHover: '#c06e11',
      buttonSecondary: '#4B5563',
      buttonSecondaryHover: '#6B7280',
      linkColor: '#f58f19',
      linkHover: '#c06e11',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#111827',
      footerBackground: '#030712',
      cardBackground: '#374151',
      borderColor: '#4B5563'
    }
  },
  gradient: {
    name: 'Gradient',
    nameBn: 'গ্রেডিয়েন্ট',
    description: 'Vibrant gradient design',
    descriptionBn: 'উজ্জ্বল গ্রেডিয়েন্ট ডিজাইন',
    icon: '🌈',
    settings: {
      primaryColor: '#f58f19',
      secondaryColor: '#c06e11',
      accentColor: '#F59E0B',
      backgroundColor: '#FFFFFF',
      textColor: '#1F2937',
      headingColor: '#111827',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'glass',
      footerStyle: 'default',
      hoverEffect: 'scale',
      gradientStart: '#c06e11',
      gradientEnd: '#dba260',
      gradientDirection: 'to-r',
      buttonPrimary: '#f58f19',
      buttonPrimaryHover: '#c06e11',
      buttonSecondary: '#bdad95',
      buttonSecondaryHover: '#f79d49',
      linkColor: '#f58f19',
      linkHover: '#c06e11',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#70a3f7',
      headerBackground: 'rgba(255,255,255,0.1)',
      footerBackground: '#1F2937',
      cardBackground: 'rgba(255,255,255,0.9)',
      borderColor: 'rgba(229,231,235,0.5)'
    }
  },
  minimal: {
    name: 'Minimal',
    nameBn: 'মিনিমাল',
    description: 'Clean and simple design',
    descriptionBn: 'পরিষ্কার এবং সহজ ডিজাইন',
    icon: '⬜',
    settings: {
      primaryColor: '#000000',
      secondaryColor: '#333333',
      accentColor: '#666666',
      backgroundColor: '#FFFFFF',
      textColor: '#000000',
      headingColor: '#000000',
      borderRadius: '0rem',
      cardStyle: 'flat',
      buttonStyle: 'square',
      headerStyle: 'transparent',
      footerStyle: 'minimal',
      hoverEffect: 'none',
      gradientStart: '#000000',
      gradientEnd: '#333333',
      gradientDirection: 'to-r',
      buttonPrimary: '#000000',
      buttonPrimaryHover: '#333333',
      buttonSecondary: '#F3F4F6',
      buttonSecondaryHover: '#E5E7EB',
      linkColor: '#000000',
      linkHover: '#333333',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#70a3f7',
      headerBackground: '#FFFFFF',
      footerBackground: '#F9FAFB',
      cardBackground: '#FFFFFF',
      borderColor: '#F3F4F6'
    }
  },
  ocean: {
    name: 'Ocean',
    nameBn: 'সাগর',
    description: 'Calm blue ocean theme',
    descriptionBn: 'শান্ত নীল সাগর থিম',
    icon: '🌊',
    settings: {
      primaryColor: '#0EA5E9',
      secondaryColor: '#0284C7',
      accentColor: '#F59E0B',
      backgroundColor: '#F0F9FF',
      textColor: '#0F172A',
      headingColor: '#0369A1',
      borderRadius: '0.75rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#0EA5E9',
      gradientEnd: '#06B6D4',
      gradientDirection: 'to-r',
      buttonPrimary: '#0EA5E9',
      buttonPrimaryHover: '#0284C7',
      buttonSecondary: '#E0F2FE',
      buttonSecondaryHover: '#BAE6FD',
      linkColor: '#0EA5E9',
      linkHover: '#0284C7',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#0EA5E9',
      headerBackground: '#FFFFFF',
      footerBackground: '#0F172A',
      cardBackground: '#FFFFFF',
      borderColor: '#BAE6FD'
    }
  },
  forest: {
    name: 'Forest',
    nameBn: 'বন',
    description: 'Green nature inspired theme',
    descriptionBn: 'সবুজ প্রকৃতি অনুপ্রাণিত থিম',
    icon: '🌲',
    settings: {
      primaryColor: '#059669',
      secondaryColor: '#047857',
      accentColor: '#F59E0B',
      backgroundColor: '#ECFDF5',
      textColor: '#064E3B',
      headingColor: '#065F46',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#059669',
      gradientEnd: '#10B981',
      gradientDirection: 'to-r',
      buttonPrimary: '#059669',
      buttonPrimaryHover: '#047857',
      buttonSecondary: '#D1FAE5',
      buttonSecondaryHover: '#A7F3D0',
      linkColor: '#059669',
      linkHover: '#047857',
      successColor: '#059669',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#064E3B',
      cardBackground: '#FFFFFF',
      borderColor: '#A7F3D0'
    }
  },
  sunset: {
    name: 'Sunset',
    nameBn: 'সূর্যাস্ত',
    description: 'Warm sunset colors',
    descriptionBn: 'উষ্ণ সূর্যাস্তের রং',
    icon: '🌅',
    settings: {
      primaryColor: '#F97316',
      secondaryColor: '#EA580C',
      accentColor: '#F59E0B',
      backgroundColor: '#FFF7ED',
      textColor: '#431407',
      headingColor: '#9A3412',
      borderRadius: '0.5rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#F97316',
      gradientEnd: '#EF4444',
      gradientDirection: 'to-r',
      buttonPrimary: '#F97316',
      buttonPrimaryHover: '#EA580C',
      buttonSecondary: '#FFEDD5',
      buttonSecondaryHover: '#FED7AA',
      linkColor: '#F97316',
      linkHover: '#EA580C',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#431407',
      cardBackground: '#FFFFFF',
      borderColor: '#FED7AA'
    }
  },
  lavender: {
    name: 'Lavender',
    nameBn: 'ল্যাভেন্ডার',
    description: 'Soft purple theme',
    descriptionBn: 'নরম বেগুনি থিম',
    icon: '💜',
    settings: {
      primaryColor: '#8B5CF6',
      secondaryColor: '#7C3AED',
      accentColor: '#F59E0B',
      backgroundColor: '#FAF5FF',
      textColor: '#4C1D95',
      headingColor: '#6D28D9',
      borderRadius: '0.75rem',
      cardStyle: 'elevated',
      buttonStyle: 'rounded',
      headerStyle: 'default',
      footerStyle: 'dark',
      hoverEffect: 'scale',
      gradientStart: '#8B5CF6',
      gradientEnd: '#C084FC',
      gradientDirection: 'to-r',
      buttonPrimary: '#8B5CF6',
      buttonPrimaryHover: '#7C3AED',
      buttonSecondary: '#EDE9FE',
      buttonSecondaryHover: '#DDD6FE',
      linkColor: '#8B5CF6',
      linkHover: '#7C3AED',
      successColor: '#10B981',
      errorColor: '#EF4444',
      warningColor: '#F59E0B',
      infoColor: '#3B82F6',
      headerBackground: '#FFFFFF',
      footerBackground: '#4C1D95',
      cardBackground: '#FFFFFF',
      borderColor: '#E9D5FF'
    }
  }
};